### ISSUE TITLE
Shared use of Random is not thread-safe

### ISSUE THREAD

**Issue by atifaziz** [alexmg/Moniker#3]
`NameGenerator` has a globally shared instance of `Random`:

https://github.com/alexmg/Moniker/blob/f5feaa838e5ed7f7eee233380fd225ba4b96f2a4/src/Moniker/NameGenerator.cs#L11

that's later used in `GetRandomEntry`:

https://github.com/alexmg/Moniker/blob/f5feaa838e5ed7f7eee233380fd225ba4b96f2a4/src/Moniker/NameGenerator.cs#L78-L82

However, per [the thread-safety section of `Random` documentation](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netframework-4.8#the-systemrandom-class-and-thread-safety), `Random` is not thread-safe:

> Instead of instantiating individual [Random] objects, we recommend that you create a single [Random] instance to generate all the random numbers needed by your app. However, [Random] objects are not thread safe. If your app calls [Random] methods from multiple threads, you must use a synchronization object to ensure that only one thread can access the random number generator at a time. If you don't ensure that the [Random] object is accessed in a thread-safe way, calls to methods that return random numbers return 0.

[Random]: https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netframework-4.8

**Comment by alexmg** [comment]
I’m sorry for the delayed response. I recently took some time to review old projects and noticed this issue. I understand it may no longer be relevant due to the time that has passed, but I wanted to let you know that the issue has been resolved, and updated versions of the packages have been published to NuGet.
